#lang racket/base
(require racket/match crypto crypto/libcrypto)
(crypto-factories libcrypto-factory)
(require x509 asn1)
(define rsadsi (OID (iso 1) (member-body 2) (us 840) (rsadsi 113549)))
(define id-ct-contentInfo (build-OID rsadsi   1  9 16 1 6))
(display id-ct-contentInfo)
(define id-cms-data (build-OID rsadsi (pkcs 1) 7 1))
(display id-cms-data)
(define id-cms-signed-data (build-OID rsadsi (pkcs 1) 7 2))
(display id-cms-signed-data)
(define id-cms-enveloped-data (build-OID rsadsi (pkcs 1) 7 3))
(display id-cms-enveloped-data)
(define id-cms-digest-data (build-OID rsadsi (pkcs 1) 7 5))
(display id-cms-digest-data)
(define id-cms-encrypted-data (build-OID rsadsi (pkcs 1) 7 6))
(display id-cms-encrypted-data)
(define id-cms-auth-data (build-OID rsadsi (pkcs 1) 9 16 1 2))
(display id-cms-auth-data)
(define id-cms-auth-enveloped-data (build-OID rsadsi (pkcs 1) 9 16 1 23))
(display id-cms-auth-enveloped-data)
(define id-cms-auth-compressed-data (build-OID rsadsi (pkcs 1) 9 16 1 9))
(display id-cms-auth-compressed-data)
